# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '08_Api_Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 08_Api_Project

  target '08_Api_ProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  pod 'Toast-Swift', '~> 5.1.1'

  target '08_Api_ProjectUITests' do
    # Pods for testing
  end

end
