# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QrCode_tutorial' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QrCode_tutorial
   pod 'QRCodeReader.swift', '~> 10.1.0'	
  target 'QrCode_tutorialTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QrCode_tutorialUITests' do
    # Pods for testing
  end

end
