# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'subway' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for subway
  pod 'Alamofire'

  target 'subwayTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'subwayUITests' do
    # Pods for testing
  end

end
