# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'oneone2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for oneone2
  # Firebase Authentication 모듈 추가
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  # 달력
  pod 'FSCalendar'

  # Modal
  pod 'FloatingPanel'

  target 'oneone2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'oneone2UITests' do
    # Pods for testing
  end
  
  post_install do |installer|
  installer.generated_projects.each do |project|
      project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
          end
      end
  end
end
end
